routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'HomeController@logout')->name('logout');
Route::group(['middleware' => array('auth')], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', 'Admin\HomeController@index')->name('home');
        Route::get('/create', 'Admin\HomeController@create')->name('create');
        Route::post('/store', 'Admin\HomeController@store')->name('store');
        Route::get('/edit/{id?}', 'Admin\HomeController@edit')->name('edit');
        Route::patch('/update/{id?}', 'Admin\HomeController@update')->name('update');
        Route::get('/delete/{id?}', 'Admin\HomeController@destroy')->name('delete');
    });
});

resources/views/admin/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Create User
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <form class="m-form m-form--fit m-form--label-align-right" id="m_form_1"
                          enctype="multipart/form-data"
                          action="{{ route('admin.store') }}" method="POST">
                        @csrf
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group row {{ $errors->has('name') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12">Username *</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type='text' class="form-control m-input" name="name"
                                               value="{{ old('name') }}"
                                               placeholder="Input username"/>
                                    </div>
                                    @if ($errors->has('name'))
                                        <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group m-form__group row {{ $errors->has('email') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12">Email *</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type="email" class="form-control m-input" name="email"
                                               value="{{ old('email') }}"
                                               placeholder="Input email"/>
                                    </div>
                                    @if ($errors->has('email'))
                                        <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group m-form__group row">
                                <label class="col-form-label col-lg-3 col-sm-12">Password *</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <label class="col-form-label col-lg-3 col-sm-12 text-danger">123456</label>
                                </div>
                            </div>
                            <div class="form-group m-form__group row {{ $errors->has('image') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12">Image</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type='file' class="form-control m-input img-choice" name="image"
                                               accept="image/*"
                                               onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group m-form__group row {{ $errors->has('image') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12"></label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <img id="blah" alt="blank-user" src="{{asset(get_const('USER_BLANK'))}}"
                                         class="img-thumbnail img-preview" style="width: 160px;">
                                    <br/>
                                    @if ($errors->has('image'))
                                        <div class="form-control-feedback">{{ $errors->first('image') }}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions">
                                <div class="row">
                                    <div class="col-lg-9 ml-lg-auto">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                        <a href="{{route('admin.home')}}" class="btn btn-secondary">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Edit User
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">
                    <form class="m-form m-form--fit m-form--label-align-right" id="m_form_1"
                          enctype="multipart/form-data"
                          action="{{ route('admin.update', $user->id) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group row {{ $errors->has('name') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12">Username *</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type='text' class="form-control m-input" name="name"
                                               placeholder="Input username" value="{{ old('name', $user->name) }}"/>
                                    </div>
                                    @if ($errors->has('name'))
                                        <div class="form-control-feedback">{{ $errors->first('name') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group m-form__group row {{ $errors->has('email') ? 'has-danger' : ''}}">
                                <label class="col-form-label col-lg-3 col-sm-12">Email *</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type="email" class="form-control m-input" name="email"
                                               placeholder="Input email" value="{{ old('email', $user->email) }}"/>
                                    </div>
                                    @if ($errors->has('email'))
                                        <div class="form-control-feedback">{{ $errors->first('email') }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group m-form__group row">
                                <label class="col-form-label col-lg-3 col-sm-12">Image</label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <div class='input-group'>
                                        <input type='file' class="form-control m-input img-choice" name="image"
                                               accept="image/*"
                                               onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group m-form__group row">
                                <label class="col-form-label col-lg-3 col-sm-12"></label>
                                <div class="col-lg-4 col-md-9 col-sm-12">
                                    <img id="blah" alt="blank-user"
                                         src="{{ get_image($user->image, get_const('USER_UPLOAD')) }}"
                                         class="img-thumbnail img-preview" style="width: 160px;">
                                    <br/>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions">
                                <div class="row">
                                    <div class="col-lg-9 ml-lg-auto">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                        <a href="{{route('admin.home')}}" class="btn btn-secondary">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                List User
                            </h3>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__body">

                    <!--begin: Search Form -->
                    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                        <div class="row align-items-center">
                            <div class="col-xl-8 order-2 order-xl-1">
                                <div class="form-group m-form__group row align-items-center">
                                    <div class="col-md-4">
                                        <div class="m-input-icon m-input-icon--left">
                                            <input type="text" class="form-control m-input" placeholder="Search..."
                                                   id="generalSearch">
                                            <span class="m-input-icon__icon m-input-icon__icon--left">
															<span><i class="la la-search"></i></span>
														</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                <a href="{{route('admin.create')}}"
                                   class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-plus"></i>
													<span>Create User</span>
												</span>
                                </a>
                                <div class="m-separator m-separator--dashed d-xl-none"></div>
                            </div>
                        </div>
                    </div>

                    <!--end: Search Form -->

                    <!--begin: Datatable -->
                    <table class="m-datatable" id="html_table" width="100%">
                        <thead>
                        <tr>
                            <th title="Field #1" data-field="Image">Image</th>
                            <th title="Field #2" data-field="Username">Username</th>
                            <th title="Field #3" data-field="Email">Email</th>
                            <th title="Field #4" data-field="Action">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td class="feed-element text-center">
                                    <img alt="image" class="img-circle" width="48px" height="48px"
                                         src="{{ get_image($user->image, get_const('USER_UPLOAD')) }}">
                                </td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <a href="{{ route('admin.delete',['id' => $user->id ]) }}"
                                       class="btn btn-danger m-btn m-btn--icon m-btn--icon-only m-btn--pill">
                                        <i class="la la-trash"></i>
                                    </a>
                                    <a href="{{ route('admin.edit',['id' => $user->id ]) }}"
                                       class="btn btn-accent m-btn m-btn--icon m-btn--icon-only m-btn--pill">
                                        <i class="la la-edit"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    <!--end: Datatable -->
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    @include('admin.layouts.message')

    <!--begin::Page Scripts -->
    <script src="{{ asset('public/js/common.js') }}" type="text/javascript"></script>
    <script src="{{ asset('public/assets/demo/default/custom/crud/metronic-datatable/base/html-table.js') }}"
            type="text/javascript">
    </script>
    <!--end::Page Scripts -->
@endsection